name: RPC endpoint doc
on:
  push:
    branches:
      - zkevm
      - stable/**
  pull_request:
    branches:
      - zkevm
      - stable/**
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Check RPC endpoints doc
        run: |
          cd ./docs/endpoints
          make check-doc